kind: pipeline
name: images
type: kubernetes

steps:
- name: build
  image: plugins/docker
  environment:
  settings:
    purge: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: zillownyc/kustomize
    build_args:
    - KUSTOMIZE_REPO=https://github.com/kubernetes-sigs/kustomize.git
    - KUSTOMIZE_COMMIT=3af514f
    - KUSTOMIZE_VERSION=v3.5.4
    targs:
    - latest
    - "3.5.4"
    - "3.5"

trigger:
  event:
  - push
  branch:
  - master
